version: '3.8'

services:
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: caddy reverse-proxy --from n8n.marcomont.com --to n8n:5678

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    restart: always
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  caddy_data:
  caddy_config:
  n8n_data: